### ISSUE TITLE
Not working for me on Chrome Version 81.0.4044.138 on Ubuntu

### ISSUE THREAD

**Issue by Kartikay26** [volca/markdown-preview#110]
When I try to open any markdown file from a local URL, it gets downloaded instead.

**Comment by volca** [comment]
Did you check option "Allow access to file URLs" in chrome://extensions?

**Comment by Kartikay26** [comment]
Yes, I did.

**Comment by volca** [comment]
I tested it with Chrome Version 83.0.4103.61 and Ubuntu 18.04. It works fine

What version is your ubuntu?

**Comment by Kartikay26** [comment]
> What version is your ubuntu?

I'm also on 18.04.
Is there any debugging output I can send you?

**Comment by volca** [comment]
* Please try to disable the extension first. and open the markdown file with Chrome again. tell me what happens 
* The full filename for the markdown file

I think it should be a MIME type detect issue.  You can open the console of Chrome to view details

* Right click on any blank place on a page in chrome
* Choose inspect -> Console
* Check Network page for details also

It may not work because chrome make a download soon

**Comment by Kartikay26** [comment]
The file gets downloaded when the extension is turned off. The full URL I am trying to open is: `file:///home/<username>/todo.md`

This is what I see in the network tab:
![image](https://user-images.githubusercontent.com/5488078/82551603-20669600-9b7e-11ea-9e19-45c3b9462088.png)
![image](https://user-images.githubusercontent.com/5488078/82551686-4724cc80-9b7e-11ea-8442-e6ce7bc25c5a.png)

I get the same thing with the extension enabled too.

**Comment by volca** [comment]
try to [Reset Chrome](https://support.google.com/chrome/answer/3296214?hl=en) to default, but sync your data first.

**Comment by volca** [comment]
I will close the issue. Reopen it if you need
